swagger: "2.0"
info:
  version: "1.0.0"
  title: "Login Page"
  description: "Login to continue. If an error occurs, please re-authenticate. Designed by Coffinxp ~/.lostsec."

host: example.com         # غيره للدومين الحقيقي لو حابب
basePath: /api
schemes:
  - https

consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json

paths:
  /Login_Page:
    post:
      tags:
        - Authentication
      summary: "Login here to continue"
      description: "Please provide your credentials to log in."
      parameters:
        - name: username
          in: formData
          description: "Your username"
          required: true
          type: string
        - name: password
          in: formData
          description: "Your password"
          required: true
          type: string
      responses:
        "200":
          description: "Login successful"
          schema:
            type: object
            properties:
              token:
                type: string
                description: "JWT or session token"
        "400":
          description: "Invalid credentials or missing parameters"
        "500":
          description: "Internal server error"

definitions:
  LoginRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    required:
      - username
      - password
