openapi: 3.0.0
info:
  title: Simple API Example
  description: A simple example for testing Swagger UI
  version: 1.0.0

servers:
  - url: https://example.com/api

paths:
  /hello:
    get:
      summary: Returns a simple greeting
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World!
