swagger: '2.0'
info:
  version: 1.0.0
  title: "<sCriPt x>(((confirm)))``</scRipt x>"
  description: "<sCriPt x>(((confirm)))``</scRipt x>"

paths:
  /Login_Page:
    post:
      summary: 
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses: 
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters. 
        '500':
          description: Internal server error.
